version: "3"
services:
        server:
                build: .
                image: heaty566/mono-grocery:latest
                container_name: mono-grocery
                networks:
                        - reverse-proxy
                expose:
                        - 80
                volumes:
                        - ./config:/app/config
networks:
        reverse-proxy:
                external: true
